### ISSUE TITLE
size mismatch for emb.weight: copying a param with shape torch.Size([25, 20]) from checkpoint, the shape in current model is torch.Size([21, 20]).

### ISSUE THREAD

**Issue by marcos914** [horsepurve/DeepRTplus#8]
When I use the prediction_emb.py to predict rt value ,I have found some questions.How can I deal with it.
python prediction_emb.py 46 param/dia_all_epo20_dim24_conv12/dia_all_epo20_dim24_conv12_filled.pt 12 data/SCX.txt

Traceback (most recent call last):
  File "prediction_emb.py", line 78, in <module>
    obse,pred1=pred_from_model(conv1,conv1,round1model,RTtest,15)
  File "prediction_emb.py", line 17, in pred_from_model
    model.load_state_dict(torch.load(param_path))
  File "/home/renzhe/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CapsuleNet:
        size mismatch for emb.weight: copying a param with shape torch.Size([25, 20]) from checkpoint, the shape in current model is torch.Size([21, 20]).

**Comment by horsepurve** [comment]
Could you try to change [line 16 in config.py](https://github.com/horsepurve/DeepRTplus/blob/213f5101000377e17ec470b9a2057b9edc92ceb2/config.py#L16) from

'''
max_length = 50
'''
to
'''
max_length = 66
'''

because 66 is the max length in "dia.txt" dataset, while 50 is for "mod.txt" dataset.

**Comment by nasseralfadly** [comment]
I have the same problem in my model
